# coding: utf-8

# flake8: noqa
"""
    Freelance Platform API

    API for managing freelancers and projects

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.assign_freelancer_to_project_request import AssignFreelancerToProjectRequest
from openapi_client.models.freelancer import Freelancer
from openapi_client.models.project import Project
